### PR TITLE
Dev/update build

### PR DESCRIPTION
**Pull request by charliewilliams**
Basic starter PR:
• Addresses some warnings to do with sprintf
• Changes made by the current version of Xcode
• Fix a warning about comparing to an integer literal always being false

### CODE REVIEW

**Review by arshiacont — APPROVED** [review]
@PhilippeCuvillier the PR looks totally fine to me! I wonder how the libz.a got there and if it's problem in the repo?! (Looks like a missing gitignore?!)
Thank you @charliewilliams :)

**Comment by charliewilliams** [comment]
Great! I don't have write access so merge at will :)

**Comment by charliewilliams** [comment]
Oh and NB I've added ignoring libz.a in the next PR

**Comment by arshiacont** [comment]
Closed in favor of #4

**Pull request closed without merging**
